### ISSUE TITLE
graph_def.ParseFromString(f.read()) google.protobuf.message.DecodeError: Error parsing message

### ISSUE THREAD

**Issue by kylinnW** [davidsandberg/facenet#1025]
I use :

python ./src/classifier.py TRAIN ./datasets/train/ ./src/models/20180402-114759.pb ./src/models/my_classifier.pkl --batch_size 1000

to train my own classifier, but receive this error...

Traceback (most recent call last):
  File "./src/classifier.py", line 170, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "./src/classifier.py", line 69, in main
    facenet.load_model(args.model)
  File "/home/wqj/facenet/src/facenet.py", line 372, in load_model
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

Please give me a hand~thanks in advance!!!

**Comment by shahryarbaki** [comment]
I got the same error when I was trying to load this [model](https://github.com/oyyd/frozen_east_text_detection.pb/blob/master/frozen_east_text_detection.pb)
