### ISSUE TITLE
 module 'tensorflow._api.v1.math' has no attribute 'floor_div'

### ISSUE THREAD

**Issue by acs121** [davidsandberg/facenet#1117]
when I ran the 'python src/validate_on_lfw.py .........' ,it throw an error.
`Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 164, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 69, in main
    image_batch, label_batch = facenet.create_input_pipeline(eval_input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder)
  File "F:\a\facenet\facenet-master\src\facenet.py", line 111, in create_input_pipeline
    image = tf.cond(get_control_flag(control[0], RANDOM_ROTATE),
  File "F:\a\facenet\facenet-master\src\facenet.py", line 140, in get_control_flag
    return tf.equal(tf.math.mod(tf.math.floor_div(control, field), 2), 1)
  File "D:\anaconda\lib\site-packages\tensorflow_core\python\util\module_wrapper.py", line 193, in __getattr__
    attr = getattr(self._tfmw_wrapped_module, name)
AttributeError: module 'tensorflow._api.v1.math' has no attribute 'floor_div'`
my tensorflow version is 1.15.0,and have been tested the 1.13.1 and 1.14.0.could you help me?

**Comment by nupnup-goddamn** [comment]
how did you solve this?

**Comment by innat** [comment]
tf.math.floordiv
