### ISSUE TITLE
Outputs of true_fn and false_fn must have the same type: float32, uint8

### ISSUE THREAD

**Issue by mohammadkhaleghy** [davidsandberg/facenet#1122]
Hi Thanks for this awesome project I have a problem when I try to train the model I get this error

`Traceback (most recent call last):
  File "src/train_softmax.py", line 582, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 129, in main
    image_batch, label_batch = facenet.create_input_pipeline(input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder)
  File "/Users/mohammadkhaleghi/AI/facenet/src/facenet.py", line 122, in create_input_pipeline
    lambda:tf.image.per_image_standardization(image))
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1274, in cond
    "%s, %s" % (x.dtype.name, y.dtype.name))
ValueError: Outputs of true_fn and false_fn must have the same type: float32, uint8` 
any idea what can be problem?

**Comment by CyruSun** [comment]
Hello, same issue here.

**Comment by pasa13142** [comment]
any solution ?

**Comment by SangriaXinji** [comment]
???

**Comment by Galahhhad** [comment]
could someone give a solution to this?

**Comment by pasa13142** [comment]
pip install tensorflow-gpu==1.7 or 1.4 or 1.14

**Comment by pohsienLiu** [comment]
This error means that your image is uint8 format, 
So you neet to add 
``` =python
 image = tf.to_float(image)
```
 in "facenet/src/facenet.py:121".

**Comment by tongvantruong** [comment]
> pip install tensorflow-gpu==1.7

cannot run it with the error: ERROR: Could not find a version that satisfies the requirement tensorflow-gpu==1.7 (from versions: none)

**Comment by tongvantruong** [comment]
same error here. I could not install tensorflow==1.7 or tensorflow-gpu==1.7. Error: Could not find a version that satisfies the requirement

**Comment by tongvantruong** [comment]
I managed to fix it by downgrading these:
1. pip install tensorflow==1.13.0rc1
2. pip install scipy==1.1.0 (optional)
3. pip install numpy==1.16.1 (optional)

**Comment by lijiale0073** [comment]
> Hi Thanks for this awesome project I have a problem when I try to train the model I get this error
> 
> `Traceback (most recent call last): File "src/train_softmax.py", line 582, in <module> main(parse_arguments(sys.argv[1:])) File "src/train_softmax.py", line 129, in main image_batch, label_batch = facenet.create_input_pipeline(input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder) File "/Users/mohammadkhaleghi/AI/facenet/src/facenet.py", line 122, in create_input_pipeline lambda:tf.image.per_image_standardization(image)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func return func(*args, **kwargs) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 1274, in cond "%s, %s" % (x.dtype.name, y.dtype.name)) ValueError: Outputs of true_fn and false_fn must have the same type: float32, uint8`
> any idea what can be problem?

**Comment by lijiale0073** [comment]
you need change:
                image = tf.cond(get_control_flag(control[0], FIXED_STANDARDIZATION),
                            lambda:(tf.cast(image, dtype=tf.float32) - 127.5)/128.0,
                            lambda:tf.image.per_image_standardization(tf.cast(image, dtype=tf.float32)))
in "facenet/src/facenet.py:122".

**Comment by Luxe6** [comment]
> you need change: image = tf.cond(get_control_flag(control[0], FIXED_STANDARDIZATION), lambda:(tf.cast(image, dtype=tf.float32) - 127.5)/128.0, lambda:tf.image.per_image_standardization(tf.cast(image, dtype=tf.float32))) in "facenet/src/facenet.py:122".

Incredibly correct
