### ISSUE TITLE
I can not "Align the LFW dataset"  in Windows10

### ISSUE THREAD

**Issue by zhjikoshlizhzc** [davidsandberg/facenet#1142]
Hello, I have a question that when I "Align the LFW dataset"  in Windows10
My program directory is under D:\Graduate\facenet-master\
When I use `python src/align/align_dataset_mtcnn.py D:\Graduate\facenet-master\data\lfw D:\Graduate\facenet-master\data\lfw_mtcnn_160 --image_size=160 --margin=32 --random_order --gpu_memory_fraction=0.25` to "Align the LFW dataset".there are an error occurs.

Can you help me to solve it?Thanks a lot!

Traceback (most recent call last):
  File "src/align/align_dataset_mtcnn.py", line 159, in <module>
    main(parse_arguments(sys.argv[1:]))

  File "src/align/align_dataset_mtcnn.py", line 47, in main
    dataset = facenet.get_dataset(args.input_dir)

  File "D:\Graduate\facenet-master\src\facenet.py", line 320, in get_dataset
    classes = [path for path in os.listdir(path_exp) \

FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'D:\\Graduate\\facenet-master\\data\\lfw'

**Comment by bilalahmed381** [comment]
Try to use ubuntu shell in window, hopefully your problem will be resolved.

**Comment by Ohad-Multisense** [comment]
try to change slash '\\' to '/' in your paths. and verify your paths
