### ISSUE TITLE
TypeError: Cannot create initializer for non-floating point type.

### ISSUE THREAD

**Issue by Asif1405** [davidsandberg/facenet#1164]
Trying to train with the Cassia Webface dataset. with the following command:

`python src/train_tripletloss.py --logs_base_dir ~/logs/facenet/ --models_base_dir ./Models/new/ --data_dir ./Dataset/processed --image_size 160 --lfw_dir ./lfw --optimizer RMSPROP --learning_rate 0.01 --weight_decay 1e-4 --max_nrof_epochs 500 --pretrained_model ./Models/facenet/20180402-114759.pb`

Getting the following error:

```
Traceback (most recent call last):
  File "src/train_tripletloss.py", line 486, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_tripletloss.py", line 134, in main
    weight_decay=args.weight_decay)
  File "D:\facenet-master\src\models\inception_resnet_v1.py", line 149, in inference
    dropout_keep_prob=keep_probability, bottleneck_layer_size=bottleneck_layer_size, reuse=reuse)
  File "D:\facenet-master\src\models\inception_resnet_v1.py", line 180, in inception_resnet_v1
    scope='Conv2d_1a_3x3')
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1159, in convolution2d
    conv_dims=2)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1057, in convolution
    outputs = layer.apply(inputs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 1700, in apply
    return self.__call__(inputs, *args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\layers\base.py", line 548, in __call__
    outputs = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 824, in __call__
    self._maybe_build(inputs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 2146, in _maybe_build
    self.build(input_shapes)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\layers\convolutional.py", line 165, in build
    dtype=self.dtype)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\layers\base.py", line 461, in add_weight
    **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py", line 529, in add_weight
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\training\tracking\base.py", line 712, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1500, in get_variable
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 1243, in get_variable
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 550, in get_variable
    return custom_getter(**custom_getter_kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1761, in layer_variable_getter
    return _model_variable_getter(getter, *args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\layers\python\layers\layers.py", line 1752, in _model_variable_getter
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\variables.py", line 351, in model_variable
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\arg_scope.py", line 182, in func_with_args
    return func(*args, **current_args)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\framework\python\ops\variables.py", line 281, in variable
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 519, in _true_getter
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 933, in _get_single_variable
    aggregation=aggregation)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 258, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 219, in _variable_v1_call
    shape=shape)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 197, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 2519, in default_variable_creator
    shape=shape)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 262, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 1688, in __init__
    shape=shape)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variables.py", line 1818, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\python\ops\variable_scope.py", line 905, in <lambda>
    partition_info=partition_info)
  File "C:\Users\MSI\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow_core\contrib\layers\python\layers\initializers.py", line 120, in _initializer
    raise TypeError('Cannot create initializer for non-floating point type.')
TypeError: Cannot create initializer for non-floating point type.
```

**Comment by MBoaretto25** [comment]
I was able to fix this. by using  image = tf.to_float(image)

**Comment by RohanMathur17** [comment]
@MBoaretto25 Where do we have to use this code? Which .py file? Please specify

**Comment by qqqsd** [comment]
> @MBoaretto25我们必须在哪里使用此代码？哪个 .py 文件？请明确说明

写在train.tripletloss.py image.set_shape()之前
