### ISSUE TITLE
No module named _pywrap_tensorflow_internal

### ISSUE THREAD

**Issue by meghasn** [davidsandberg/facenet#1167]
Initially I had tensorflow 2.3 but due to

module 'tensorflow' has no attribute 'GPUOptions'

changed to tensorflow 1.7

and now iam getting the following error and I am unable to proceed with my proj.Though they have mentioned the link I am kind off lost.If anyone has any suggestions regarding the issue it would be much appreciated.Thank You in advance

ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\pnc\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\pnc\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\pnc\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by rlrahulkanojia** [comment]
remove tensorflow completely,

`pip uninstall tensorflow'
`pip uninstall tensorflow-gpu'

then install tensorflow, it should work fine.

**Comment by Myriamesf75** [comment]
It worked for me after doing this command : 

```
pip install tensorflow-gpu == 1.15.5 
```

I was previously with tensorflow-gpu 1.15.0 when it was showing the error
