### ISSUE TITLE
index 'i' exceeds class_indices[i]

### ISSUE THREAD

**Issue by hanybo** [davidsandberg/facenet#1176]
In the file [train_tripletloss.py](https://github.com/AzureWoods/faceRecognition-yolo-facenet) there is a function `def sample_people` inside which there is a while loop with the following code `class_index = class_indices[i]`. I have only two classes and 3000 images per class (3000 in the first and 2999 in the second). I realized that no matter how much I change the variables _(people_per_batch,batch_size,images_per_person)_ . I get the same error which is

`File "train_tripletloss.py", line 332, in sample_people`
    `class_index = class_indices[i]`
`IndexError: index 2 is out of bounds for axis 0 with size 2`

I can realize that the issue is because I have only two classes _nrof_classes=2_ and I append them with the `np.arange(nrof_classes)`. But the `while` loop runs for more than 2 iterations and obviously since the classes are only 2 in the 3rd iteration the code breaks. 

I checked in a similar issue [here](https://github.com/davidsandberg/facenet/issues/18) which as far as I can see does not solve the issue. 

Could you provide me with some help?

My Stacktrace is :

Traceback (most recent call last):
`  File "train_tripletloss.py", line 491, in <module>`
 `   main(parse_arguments(sys.argv[1:]))`
 ` File "train_tripletloss.py", line 191, in main`
  `  args.embedding_size, anchor, positive, negative, triplet_loss)`
 ` File "train_tripletloss.py", line 217, in train`
 `   image_paths, num_per_class = sample_people(dataset, args.people_per_batch, args.images_per_person)`
`  File "train_tripletloss.py", line 332, in sample_people`
 `   class_index = class_indices[i]`
`IndexError: index 2 is out of bounds for axis 0 with size 2`

**Comment by sassiaicha** [comment]
hey @hanybo !
I have the same problem and I can't find a solution.
If you found a fix to it. I would be grateful if you help me about it.
thank you in advance.

**Comment by thaiph99** [comment]
> hey @hanybo !
> I have the same problem and I can't find a solution.
> If you found a fix to it. I would be grateful if you help me about it.
> thank you in advance.

you can check argument '--people_per_batch' and '--images per_person' , which was created default

**Comment by FifthWit** [comment]
Hey, I'm very late to this but, I am running into the same error, and I find the wording too vague, could you explain, like am I supposed to change the --people_per_batch I'm not sure what is being asked. Thank you in advance!
