### ISSUE TITLE
when I run train_tripletloss.py , I met this

### ISSUE THREAD

**Issue by qqqsd** [davidsandberg/facenet#1204]

**Comment by qqqsd** [comment]
Running forward pass on sampled images: 165.140
Selecting suitable triplets for training
(nrof_random_negs, nrof_triplets) = (17714, 17667): time=168.161 seconds
Traceback (most recent call last):
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1375, in _do_call
    return fn(*args)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1360, in _run_fn
    target_list, run_metadata)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1453, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 256 values, but the requested shape requires a multiple of 384
	 [[{{node Reshape}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/cx/FaceNet/train_tripletloss.py", line 530, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "F:/cx/FaceNet/train_tripletloss.py", line 187, in main
    args.embedding_size, anchor, positive, negative, triplet_loss)
  File "F:/cx/FaceNet/train_tripletloss.py", line 270, in train
    feed_dict=feed_dict)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 968, in run
    run_metadata_ptr)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1191, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1369, in _do_run
    run_metadata)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\client\session.py", line 1394, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 256 values, but the requested shape requires a multiple of 384
	 [[node Reshape (defined at F:/cx/FaceNet/train_tripletloss.py:127) ]]

Errors may have originated from an input operation.
Input Source operations connected to node Reshape:
 embeddings (defined at F:/cx/FaceNet/train_tripletloss.py:125)

Original stack trace for 'Reshape':
  File "F:/cx/FaceNet/train_tripletloss.py", line 530, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "F:/cx/FaceNet/train_tripletloss.py", line 127, in main
    anchor, positive, negative = tf.unstack(tf.reshape(embeddings, [-1, 3, args.embedding_size]), 3, 1)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\util\dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\array_ops.py", line 195, in reshape
    result = gen_array_ops.reshape(tensor, shape, name)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 8377, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 750, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 3536, in _create_op_internal
    op_def=op_def)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 1990, in __init__
    self._traceback = tf_stack.extract_stack()


Process finished with exit code 1
