### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 512)) while a minimum of 1 is required.`

### ISSUE THREAD

**Issue by KangChou** [davidsandberg/facenet#1212]
`Loading feature extraction model
Model filename: /data/my_project/facenet/pat_model/20180402-114759.pb
Calculating features for images
Training classifier
Traceback (most recent call last):
  File "/data/my_project/facenet/src/classifier.py", line 171, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/data/my_project/facenet/src/classifier.py", line 97, in main
    model.fit(emb_array, labels)
  File "/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py", line 149, in fit
    accept_large_sparse=False)
  File "/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 747, in check_X_y
    estimator=estimator)
  File "/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py", line 577, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 512)) while a minimum of 1 is required.`

**Comment by AlexeyAL1e** [comment]
Please let me know if you managed to resolve this issue? @KangChou @davidsandberg
