### ISSUE TITLE
About tensorflow -v2.8.0, I have a error.

### ISSUE THREAD

**Issue by ygpusr** [davidsandberg/facenet#1232]
Traceback (most recent call last):
  File "D:\pycharmworkspace\face_recognition\tensorflow_face2.0\venv\lib\site-packages\tensorflow\python\client\session.py", line 1377, in _do_call
    return fn(*args)
  File "D:\pycharmworkspace\face_recognition\tensorflow_face2.0\venv\lib\site-packages\tensorflow\python\client\session.py", line 1359, in _run_fn
    self._extend_graph()
  File "D:\pycharmworkspace\face_recognition\tensorflow_face2.0\venv\lib\site-packages\tensorflow\python\client\session.py", line 1400, in _extend_graph
    tf_session.ExtendSession(self._session)
tensorflow.python.framework.errors_impl.InvalidArgumentError: input resource[0] expected type resource != float, the type of assignmovingavg_readvariableop_inceptionresnetv1_conv2d_1a_3x3_batchnorm_moving_mean[0]
	In {{node AssignMovingAvg/AssignSubVariableOp}}

**Comment by Jawabreh0** [comment]
explain the error you got and how rather than pasting the error code so we can help, no one gonna read the error message you gave
