### ISSUE TITLE
Error "You must feed a value for placeholder tensor 'phase_train' with dtype bool." 

### ISSUE THREAD

**Issue by jackjack2** [davidsandberg/facenet#144]
I get error when trying to compare two images through compare.py. 
```
python compare.py ../20170131-234652/ ../data/images/Anthony_Hopkins_0001.jpg ../data/images/Anthony_Hopkins_0002.jpg 

/home/jack/.local/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
Creating networks and loading parameters
Model directory: ../20170131-234652/
Metagraph file: model-20170131-234652.meta
Checkpoint file: model-20170131-234652.ckpt-250000
Traceback (most recent call last):
  File "compare.py", line 129, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "compare.py", line 59, in main
    emb = sess.run(embeddings, feed_dict=feed_dict)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'phase_train' with dtype bool
	 [[Node: phase_train = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'phase_train', defined at:
  File "compare.py", line 129, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "compare.py", line 50, in main
    facenet.load_model(args.model_dir, meta_file, ckpt_file)
  File "/home/jack/Desktop/facenet-master/src/facenet.py", line 368, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1526, in import_meta_graph
    **kwargs)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 502, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    op_def=op_def)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/jack/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'phase_train' with dtype bool
	 [[Node: phase_train = Placeholder[dtype=DT_BOOL, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by duesencode** [comment]
I experience a the same issue on `validate_on_lfw.py`

Any suggestions how to solve this?

**Comment by jackjack2** [comment]
Yep. That's works. Thank you!
