### ISSUE TITLE
Training own dataset: sess.run() stuck and never returns from face_train_classifier.py

### ISSUE THREAD

**Issue by psakamoori** [davidsandberg/facenet#149]
Hi,

I just took my own data set and followed below steps

  1.  Align the dataset
  2. Use below command to train ....code stuck at sess.run in face_train_classisifer.py (tried both jpg and png files)

Command used:
python facenet_train_classifier.py --logs_base_dir ~/logs/facenet/ --models_base_dir models/facenet/ --data_dir ../data/caltech/mtcnnalign_182 --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir ../data/caltech/mtcnnalign_160 --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file ../data/learning_rate_schedule_classifier_long.txt --weight_decay 5e-5 --center_loss_factor 1e-4 --center_loss_alfa 0.9

Error Log:
Model directory: models/facenet/20170209-161412
Log directory: /home/psakhamo/logs/facenet/20170209-161412
LFW directory: ../data/caltech/mtcnnalign_160

Total number of classes: 28
Total number of examples: 1329
Building training graph
Building evaluation graph
GPU_OPTIONS per_process_gpu_memory_fraction: 1.0

I tensorflow/core/common_runtime/gpu/gpu_device.cc:951] Found device 0 with properties:
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:03:00.0
Total memory: 7.92GiB
Free memory: 7.67GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:972] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:03:00.0)
E tensorflow/stream_executor/cuda/cuda_driver.cc:965] failed to allocate 7.92G (8499691520 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
Running training
W tensorflow/core/framework/op_kernel.cc:968] Failed precondition: /
W tensorflow/core/framework/op_kernel.cc:968] Not found: h
ERROR:tensorflow:Exception in QueueRunner: /
         [[Node: ReadFile_4 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive/assert_less/Assert/AssertGuard/Assert/_122 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_63_assert_positive/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_4', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): /
         [[Node: ReadFile_4 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive/assert_less/Assert/AssertGuard/Assert/_122 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_63_assert_positive/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

ERROR:tensorflow:Exception in QueueRunner: h
         [[Node: ReadFile_6 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive_7/assert_less/Assert/AssertGuard/Assert/_418 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_40_assert_positive_7/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_6', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): h
         [[Node: ReadFile_6 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive_7/assert_less/Assert/AssertGuard/Assert/_418 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_40_assert_positive_7/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
NotFoundError: h
         [[Node: ReadFile_6 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive_7/assert_less/Assert/AssertGuard/Assert/_418 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_40_assert_positive_7/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_6', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): h
         [[Node: ReadFile_6 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive_7/assert_less/Assert/AssertGuard/Assert/_418 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_40_assert_positive_7/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
FailedPreconditionError: /
         [[Node: ReadFile_4 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive/assert_less/Assert/AssertGuard/Assert/_122 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_63_assert_positive/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_4', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): /
         [[Node: ReadFile_4 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: assert_positive/assert_less/Assert/AssertGuard/Assert/_122 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_63_assert_positive/assert_less/Assert/AssertGuard/Assert", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

W tensorflow/core/framework/op_kernel.cc:968] Not found: o
ERROR:tensorflow:Exception in QueueRunner: o
         [[Node: ReadFile_5 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]

Caused by op u'ReadFile_5', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): o
         [[Node: ReadFile_5 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]

Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
NotFoundError: o
         [[Node: ReadFile_5 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]

Caused by op u'ReadFile_5', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): o
         [[Node: ReadFile_5 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]

W tensorflow/core/framework/op_kernel.cc:968] Not found: m
ERROR:tensorflow:Exception in QueueRunner: m
         [[Node: ReadFile_7 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: Shape_28/_1021 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_302_Shape_28", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_7', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): m
         [[Node: ReadFile_7 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: Shape_28/_1021 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_302_Shape_28", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner.py", line 225, in _run
    sess.run(enqueue_op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
NotFoundError: m
         [[Node: ReadFile_7 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: Shape_28/_1021 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_302_Shape_28", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'ReadFile_7', defined at:
  File "facenet_train_classifier.py", line 361, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 141, in main
    args.lfw_batch_size, None, False, False, args.nrof_preprocess_threads, shuffle=False)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 125, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/psakhamo/face_recog/facenet/src/facenet.py", line 106, in read_images_from_disk
    file_contents = tf.read_file(input_queue[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 107, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): m
         [[Node: ReadFile_7 = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](input_producer_1/Gather)]]
         [[Node: Shape_28/_1021 = _HostRecv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_302_Shape_28", tensor_type=DT_INT32, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

......
........

Epoch: [0][96/100]      Time 0.653      Loss 7.944      RegLoss 4.733
Epoch: [0][97/100]      Time 0.643      Loss 8.566      RegLoss 4.719
Epoch: [0][98/100]      Time 0.598      Loss 8.373      RegLoss 4.696
Epoch: [0][99/100]      Time 0.600      Loss 8.383      RegLoss 4.721
Epoch: [0][100/100]     Time 0.601      Loss 7.880      RegLoss 4.681
Saving variables
Variables saved in 1.55 seconds
MetaGraph_fileName models/facenet/20170209-161412/model-20170209-161412.meta
Saving metagraph
Metagraph saved in 25.90 seconds
.....
.
....
Runnning forward pass on LFW images

Never returns from here....

Any one seen this??

**Comment by psakamoori** [comment]
Trying to validate my trained model with validate_on_lfw.py

**Comment by davidsandberg** [comment]
For some reason ReadFile in the input pipeline fails, possibly due to some corrupt file in the training or testing dataset. But it looks like the majority of the files are ok since you can actually do some training. I don't know if there is a simple way to find the corrupt files and when I had a similar problem I ended up only using a part of the dataset and did divide-an-conquer to find the corrupt file. But maybe it's possible to get tensorflow to print file names before attempting to read them.
I'm afraid I can't help you much more.

**Comment by psakamoori** [comment]
Thank you for the reply.
No Problem.
For now, evaluating using "validate_on_lfw.py" instead of calling evaluate from "facenet_train_classifier.py" solved the problem
Training with "facenet_train_classifier.py" and evaluating with "validate_on_lfw.py".

**Comment by liuguiyangnwpu** [comment]
hi,
```
readfile = "/Users/liuguiyang/Documents/CodeProj/PyProj/dtb/dtb/inputs/data/Cifar10/test.list"

def test01():
    with tf.Graph().as_default():

        def read_img_png(filename_que):
            reader = tf.TextLineReader(skip_header_lines=False)
            key, img_path = reader.read(filename_queue)
            print(key, img_path)
            raw_img = tf.image.decode_png(tf.read_file(img_path), channels=3)
            return raw_img

        filenames = []
        with open(readfile, 'r') as h:
            filenames = [f.strip() for f in h.readlines()]
        filename_queue = tf.train.string_input_producer(filenames)
        raw_img = read_img_png(filename_queue)

        # raw_img = tf.image.convert_image_dtype(raw_img, dtype=tf.float32)
        # raw_img.set_shape((32,32,3))
        init_op = tf.tables_initializer()
        with tf.Session() as sess:
            sess.run(init_op)

            coord = tf.train.Coordinator()
            threads = tf.train.start_queue_runners(coord=coord)

            for i in range(10):
                print(sess.run([raw_img]))

            coord.request_stop()
            coord.join(threads=threads)
```

I want to run this program  to fetch the png image from the image.list. But there are some problems, which i can't fix.

```
➜  scripts git:(CAE) ✗ python3 tune-airplane.py
Tensor("ReaderReadV2:0", shape=(), dtype=string) Tensor("ReaderReadV2:1", shape=(), dtype=string)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: \udc89PNG
	 [[Node: ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tune-airplane.py", line 60, in <module>
    test01()
  File "tune-airplane.py", line 43, in test01
    print(sess.run([raw_img]))
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: \udc89PNG
	 [[Node: ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1)]]

Caused by op 'ReadFile', defined at:
  File "tune-airplane.py", line 60, in <module>
    test01()
  File "tune-airplane.py", line 31, in test01
    raw_img = read_img_png(filename_queue)
  File "tune-airplane.py", line 24, in read_img_png
    raw_img = tf.image.decode_png(tf.read_file(img_path), channels=3)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/ops/gen_io_ops.py", line 202, in read_file
    result = _op_def_lib.apply_op("ReadFile", filename=filename, name=name)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): \udc89PNG
	 [[Node: ReadFile = ReadFile[_device="/job:localhost/replica:0/task:0/cpu:0"](ReaderReadV2:1)]]
```
