### ISSUE TITLE
compare 2 images

### ISSUE THREAD

**Issue by kaishijeng** [davidsandberg/facenet#16]
Do you have a similar utility to compare two jpeg face images and determine whether both are the same person or not, like compare.py in openface?

Thanks,

**Comment by davidsandberg** [comment]
Currently there is no utility like that. It wouldn't be too much work to modify for example "validate_on_lfw" to take two jpeg images instead, but that would assume that the images has already  been face-aligned. A nicer solution would be to integrate face alignment, for example from openface, but that would be some more work. But definitly worth doing!

**Comment by kaishijeng** [comment]
Thanks

**Comment by kaishijeng** [comment]
I modify validate_on_lfw.py for comparing 2 aligned face images and have
one question about dim of  features for each person. Based on the code
below if images contains one face image,
feed_dict = { images_placeholder: images, phase_train_placeholder: False }
emb1 = sess.run([embeddings], feed_dict=feed_dict)

I expect emb1 should be one dim array with size 128. But emb1.shape shows
 9x128.
Does facenet need 9x128 values/person face for recognition?
Openface uses 128 values/person face.

Thanks,
FC

**Comment by davidsandberg** [comment]
I guess you have changed the batch_size to 2? If that is the case you should be able to get a tensor with the two embeddings of size 2x128 (if i remember correctly). And then you can just compute the l2 distance between the embeddings.

**Comment by kaishijeng** [comment]
I change batch_size to 1 so that I can compute emb for each image.
WIth this change, I expect dim of   return from sess.run should be 1x128,
but it is 9x128 which is weird

FC

**Comment by kaishijeng** [comment]
If I set batch_size =2, then dim of return from sess.run becomes 18x128.
Why is it not 2x128?

FC

**Comment by davidsandberg** [comment]
Hi again,
I tried to set batch_size = 1 and look at the dimensions of some tensors, and they are as expected:
images_placeholder: Tensor: Tensor("input:0", shape=(1, 96, 96, 3), dtype=float32)
embeddings: Tensor: Tensor("embeddings:0", shape=(1, 128), dtype=float32)
Have you checked the same tensors?

**Comment by kaishijeng** [comment]
My aligned face image size is 144. If I redo face alignment to size 96, the
embeddings shape is (1,128) for one image.
Not sure why face image 144 will make embeddedings shape (9, 128)

**Comment by davidsandberg** [comment]
Ok, that makes more sense. The function that generates the inference graph only works for input images of size 96. The key is the line
`resh1 = tf.reshape(pool6, [-1, 896])` 
With 96 pixel images the pool6 shape is (1, 1, 1, 896)
but with 144 pixel images it is(1, 3, 3, 896).
It would probably be better to throw an exception when this happens.

**Comment by kaishijeng** [comment]
Thanks for compare.py utility.
Is your pretrained model,   model-20160306.ckpt-500000,  not comparable with the latest code? I got the following error when running compare.py:

Traceback (most recent call last):
  File "./compare.py", line 80, in <module>
    main()
  File "./compare.py", line 58, in main
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1104, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 332, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 572, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 652, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 672, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "incept5b/in4_conv1x1_55/weights/ExponentialMovingAverage" not found in checkpoint files ./models/facenet/20160514-234418/model.ckpt-1000
         [[Node: save/restore_slice_331 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_331/tensor_name, save/restore_slice_331/shape_and_slice)]]
Caused by op u'save/restore_slice_331', defined at:
  File "./compare.py", line 80, in <module>
    main()
  File "./compare.py", line 52, in main
    saver = tf.train.Saver(ema.variables_to_restore())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 845, in __init__
    restore_sequentially=restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 515, in build
    filename_tensor, vars_to_save, restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 271, in _AddRestoreOps
    values = self.restore_op(filename_tensor, vs, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 186, in restore_op
    preferred_shard=preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 201, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 325, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 693, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2186, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1170, in __init__
    self._traceback = _extract_stack()

**Comment by davidsandberg** [comment]
No, there's a new model that is equivalent that you could download from
https://drive.google.com/file/d/0B5MzpY9kBtDVVFRyU2JCVmZXUEk/view?usp=sharing

**Comment by kaishijeng** [comment]
It works OK with new model

Thanks

**Comment by ManyuChang** [comment]
@kaishijeng   Have you do it successfully?
