### ISSUE TITLE
Is it compatible with tensorflow 1.0?

### ISSUE THREAD

**Issue by richardhahahaha** [davidsandberg/facenet#165]
```
~/work/facenet/src$ ./train.sh 
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Model directory: train/models/20170217-203220
Log directory: train/logs/20170217-203220
LFW directory: lfw_160/lfw
Skipped 6000 image pairs
Traceback (most recent call last):
  File "facenet_train_classifier.py", line 442, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 122, in main
    for filename in tf.unpack(filenames):
AttributeError: 'module' object has no attribute 'unpack'

~/work/facenet/src$ python -c "import tensorflow as tf; print tf.VERSION"
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
1.0.0

```

**Comment by ae86208** [comment]
[Currently this repo is compatible with Tensorflow r0.12.](https://github.com/davidsandberg/facenet#tensorflow-release)

**Comment by davidsandberg** [comment]
The repo has now been updated to TF r1.0.

**Comment by Mikebarson** [comment]
@davidsandberg I'm still getting the same error as he is. I've already pulled the updates for Tensorflow r1.0. But I'm still getting the same error.
