### ISSUE TITLE
Error align_dataset_mtcnn.py

### ISSUE THREAD

**Issue by silvaph** [davidsandberg/facenet#166]
Hi, David,

thanks a lot for releasing your code to us. I was following your tutorial available on  ["Classifier training of inception resnet v1"](https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1). I was trying to run the align_dataset_mtcnn.py code in a small dataset (2 people/classes and 10 examples for each one) to understand the process better. The images folder structure is like:
(1) Train
(1.1) Person1
(1.2) Person2

I executed the code with path/to/Train/ to test and ended up with following error raised:

`Traceback (most recent call last):
  File "../src/align/align_dataset_mtcnn.py", line 147, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "../src/align/align_dataset_mtcnn.py", line 59, in main
    pnet, rnet, onet = align.detect_face.create_mtcnn(sess, '../../data/')
  File "/root/pdi/framework/tensorflow/facenet/src/align/detect_face.py", line 279, in create_mtcnn
    pnet = PNet({'data':data})
  File "/root/pdi/framework/tensorflow/facenet/src/align/detect_face.py", line 73, in __init__
    self.setup()
  File "/root/pdi/framework/tensorflow/facenet/src/align/detect_face.py", line 219, in setup
    .conv(3, 3, 10, 1, 1, padding='VALID', relu=False, name='conv1')
  File "/root/pdi/framework/tensorflow/facenet/src/align/detect_face.py", line 51, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/root/pdi/framework/tensorflow/facenet/src/align/detect_face.py", line 154, in conv
    kernel = self.make_var('weights', shape=[k_h, k_w, c_i // group, c_o])
TypeError: unsupported operand type(s) for //: 'Dimension' and 'int'`

Am I doing something wrong?

Kind regards,
Pedro Silva

**Comment by davidsandberg** [comment]
Hi @silvaph,
I didn't manage to reproduce the problem with tensorflow r0.12. Anyway I added explicit type casts between Dimension and int (a48766c1fb84f83c99ae563850eaab79f3b5dbcc). Hopefully that will solve the problem.

**Comment by silvaph** [comment]
Hi @davidsandberg,

Thank you very much for your reply, I was with the newest version of tensorflow, when I downgrade to r0.12 it started to work, my fault.

Thanks.
