### ISSUE TITLE
Unable to continue training from pretrained 20170131-005910 and 20170131-234652 Inception-ResNet-v1 models

### ISSUE THREAD

**Issue by dkozlov** [davidsandberg/facenet#185]
20170131-005910 pretrained model: https://drive.google.com/file/d/0B5MzpY9kBtDVRDFsRk8xaVI1MUU/view
facenet revision:
latest commit 1789ce2feee8b2b713a98e6c5bd8882609fbec4d
tensorflow-gpu==1.0.0

python facenet_train_classifier.py --logs_base_dir logs/facenet/ --models_base_dir models/facenet/ --data_dir /data/CASIA-maxpy-mtcnnpy-182/ --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir /data/lfw-mtcnn-tf/ --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file ../data/learning_rate_schedule_classifier_casia.txt --weight_decay 5e-5 --center_loss_factor 1e-4 --center_loss_alfa 0.9 --pretrained_model /data/Downloads/20170131-005910/model-20170131-005910.ckpt-80000

Model directory: models/facenet/20170301-210414
Log directory: logs/facenet/20170301-210414
Pre-trained model: /data/Downloads/20170131-005910/model-20170131-005910.ckpt-80000
LFW directory: /data/lfw-mtcnn-tf/
Total number of classes: 10575
Total number of examples: 453911
Building training graph
W tensorflow/core/framework/op_kernel.cc:993] Not found: Key Bottleneck/BatchNorm/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Traceback (most recent call last):
  File "facenet_train_classifier.py", line 460, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 220, in main
    saver.restore(sess, pretrained_model)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key Bottleneck/BatchNorm/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_230/_815 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2010_save/RestoreV2_230", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2', defined at:
  File "facenet_train_classifier.py", line 460, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 203, in main
    saver = tf.train.Saver(tf.trainable_variables(), max_to_keep=3)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1051, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1081, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key Bottleneck/BatchNorm/beta not found in checkpoint
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_230/_815 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_2010_save/RestoreV2_230", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by davidsandberg** [comment]
Hi @dkozlov!
I have uploaded new pretrained models that also have the bottleneck layer.
BUT, it will probably be tricky to resume training of a pretrained model without the exact same classes used in the last classification layer. And for that you would need the exact same dataset as I used for training. But you should be able to resume training for a model that you are training yourself. Or you can use the same parameter in `facenet_train` to resume training of a pretrained model using triplet loss.

**Comment by dkozlov** [comment]
Thank you!
