### ISSUE TITLE
Error runnig a frozen graph of the 128-dimensional embeddings model

### ISSUE THREAD

**Issue by mhaghighat** [davidsandberg/facenet#195]
I froze the new 128-dimensional embeddings model using the freeze_graph.py, but at the time of running the session, it gives this error:

`Failed precondition: Attempting to use uninitialized value Bottleneck/BatchNorm/moving_variance
  [[Node: Bottleneck/BatchNorm/moving_variance/read = Identity[T=DT_FLOAT, _class=["loc:@Bottleneck/BatchNorm/moving_variance"], _device="/job:localhost/replica:0/task:0/cpu:0"](Bottleneck/BatchNorm/moving_variance)]]
`

Should I change something in freeze_graph.py?

**Comment by ugtony** [comment]
@mhaghighat 
It has been discussed in #108. 
The new bottleneck nodes should be added to the whitelist in freeze_graph.py:
```if node.name.startswith('InceptionResnetV1') or node.name.startswith('embeddings') or node.name.startswith('phase_train') or node.name.startswith('Bottleneck'):```

**Comment by mhaghighat** [comment]
Thanks a lot, @ugtony.

**Comment by RakshakTalwar** [comment]
@ugtony 

with the updated freeze_graph.py I'm getting this KeyError:

`Model directory: models/20170216-091149/
Metagraph file: model-20170216-091149.meta
Checkpoint file: model-20170216-091149.ckpt-250000
Traceback (most recent call last):
 File "freeze_graph.py", line 96, in <module>
   main(parse_arguments(sys.argv[1:]))
 File "freeze_graph.py", line 48, in main
   saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file), clear_devices=True)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1526, in import_meta_graph
   **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 502, in import_scoped_meta_graph
   producer_op_list=producer_op_list)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
   op_def = op_dict[node.op]
KeyError: u'VariableV2'`

**Comment by RakshakTalwar** [comment]
@ugtony @mhaghighat 

I'm getting this error with the new freeze_graph.py

```
Model directory: models/20170216-091149/
Metagraph file: model-20170216-091149.meta
Checkpoint file: model-20170216-091149.ckpt-250000
Traceback (most recent call last):
 File "freeze_graph.py", line 96, in <module>
   main(parse_arguments(sys.argv[1:]))
 File "freeze_graph.py", line 48, in main
   saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file), clear_devices=True)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1526, in import_meta_graph
   **kwargs)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 502, in import_scoped_meta_graph
   producer_op_list=producer_op_list)
 File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
   op_def = op_dict[node.op]
KeyError: u'VariableV2'
```

**Comment by mhaghighat** [comment]
@RakshakTalwar,
It happened to me too. I updated to TensorFlow r1.0, and it worked.

**Comment by RakshakTalwar** [comment]
@mhaghighat thanks for letting me know!

**Comment by adwin5** [comment]
confirmed.
it doesn't work for tf0.12 but for tf r1.0.1
