### ISSUE TITLE
when I run "validate_on_lfw.py",the error is :

### ISSUE THREAD

**Issue by yanmenglu** [davidsandberg/facenet#201]
python validate_on_lfw.py ~/facenet/datasets/lfw/lfw_mtcnnpy_160 ~/Desktop/FaceDetection/20170131-234652
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:111] successfully opened CUDA library libcurand.so locally
E tensorflow/stream_executor/cuda/cuda_driver.cc:491] failed call to cuInit: CUDA_ERROR_UNKNOWN
I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:140] kernel driver does not appear to be running on this host (cylan-System-Product-Name): /proc/driver/nvidia/version does not exist
Model directory: /home/yml/Desktop/FaceDetection/20170131-234652
Metagraph file: model-20170131-234652.meta
Checkpoint file: model-20170131-234652.ckpt-250000
Traceback (most recent call last):
  File "validate_on_lfw.py", line 116, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "validate_on_lfw.py", line 63, in main
    facenet.load_model(args.model_dir, meta_file, ckpt_file)
  File "/home/yml/facenet/src/facenet.py", line 368, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1711, in import_meta_graph
    read_meta_graph_file(meta_graph_or_file), clear_devices)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1598, in _import_meta_graph_def
    input_graph_def, name="", producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'Reciprocal'
What  is this meaning?And How do I solve it ?

**Comment by yanmenglu** [comment]
What "KeyError: u'Reciprocal' "is meaning?How to solve that?

**Comment by yanmenglu** [comment]
I solve that.It need to update to tenosrflow 1.0.
