### ISSUE TITLE
OutOfRangeError train_softmax

### ISSUE THREAD

**Issue by siebertlooije** [davidsandberg/facenet#273]
Hello,

First of all, thanks for the good explanations in this repository. 
I try to use the Inception_resnet_v2 with the Casia mtcnn aligned dataset, but I'm getting the following errors after a couple of epoch (so not at the start ~around the 10 epoch):

tensorflow/core/framework/op_kernel.cc:993] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: batch_join = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, _recv_batch_size_0)]]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: batch_join = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, _recv_batch_size_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/train_softmax.py", line 468, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 236, in main
    total_loss, train_op, summary_op, summary_writer, regularization_losses, args.learning_rate_schedule_file)
  File "src/train_softmax.py", line 307, in train
    err, _, step, reg_loss = sess.run([loss, train_op, global_step, regularization_losses], feed_dict=feed_dict)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: batch_join = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, _recv_batch_size_0)]]

Caused by op 'batch_join', defined at:
  File "src/train_softmax.py", line 468, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 144, in main
    allow_smaller_final_batch=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/input.py", line 1018, in batch_join
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/input.py", line 700, in _batch_join
    dequeued = queue.dequeue_up_to(batch_size, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 499, in dequeue_up_to
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 1402, in _queue_dequeue_up_to_v2
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 48, current size 0)
	 [[Node: batch_join = QueueDequeueUpToV2[component_types=[DT_FLOAT, DT_INT64], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, _recv_batch_size_0)]]

The command that I'am running is the following : 

python3 src/train_softmax.py --logs_base_dir /path/to/facenet/logs/ \
  --models_base_dir /path/to/facenet/ --data_dir /path/to/casia-maxpy-clean/CASIA_mtcnn_182/ \
  --image_size 160 --model_def models.inception_resnet_v2 --lfw_dir /path/to/datasets/lfw/lfw_mtcnnpy_160/ \
  --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip \
  --learning_rate_schedule_file data/learning_rate_schedule_classifier_casia.txt --weight_decay 5e-5 --center_loss_factor 1e-4 --center_loss_alfa 0.9 \
  --batch_size 48 --epoch_size 2000

I already got the last update from the repository, so  issues #247, #210, #105, #84 are not feasible for this problem . It also is not #205 because I'm only using png images.

The number of images are : 

Total number of classes: 10252
Total number of examples: 434527

Another question is, why did you change the slice_input_producer to the range_input_producer. What is the real benefit of this ?

Thanks !

**Comment by davidsandberg** [comment]
Hi @siebertlooije!
First of all, thanks for a very well written trouble report!
For the actual problem I cannot say for sure what the problem is. However, I have experienced a problem where a few of the .png files in the dataset becomes corrupted. When the corrupted files are read by the input pipeline the pre-processing thread crashes. And when all pre-processing threads have crashed there is no thread to fill up the batch, and batch_join will crash the main thread.
I don't have an easy way of finding corrupt image files since it's not so easy to see from the error messages. One way of finding out would be to make a small script to just read image files in the dataset. One such script can be found in `tmp/dataset_read_speed.py`

For your question the main reason of having the input pipeline like this was that I wanted to be able to reuse the same pipeline also for train_tripletloss. This has not really happend yet but hopefully it will in a not too distant future.

**Comment by siebertlooije** [comment]
Thanks for the quick response. 
Ok, that was the only thing I did not checked yet and it seems that there is atleast one corrupted file... 
Maybe it would be wise to add just one single line in the documentation of the mtcnn aligning, that it could give corrupted files. So everyone knows that it could happen.

Ok, yeah that makes sense. I think this ticket can be closed now.
