### ISSUE TITLE
classifier problem

### ISSUE THREAD

**Issue by buaaswf** [davidsandberg/facenet#284]
Model filename: /home/swf/work/0509/facenet/models/facenetclean/20170512-110547/20170512-110547.pb
Traceback (most recent call last):
  File "src/classifier.py", line 170, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/classifier.py", line 69, in main
    facenet.load_model(args.model)
  File "/home/swf/work/0512/facenet/src/facenet.py", line 375, in load_model
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'FIFOQueueV2'

**Comment by davidsandberg** [comment]
Hi,
This sounds like a tensorflow version problem. This repo is currently tested against TF 1.0. Which version are you using?

**Comment by buaaswf** [comment]
I update my tensorflow to TF.1.0, the problem disappeared.
