### ISSUE TITLE
ResourceExhaustedError 

### ISSUE THREAD

**Issue by luckyboysmith** [davidsandberg/facenet#298]
when i run the code
CUDA_VISIBLE_DEVICES=1 python src/train_softmax.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir ~/data/casia-align --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir /home/david/datasets/lfw/lfw_mtcnnalign_160 --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file data/learning_rate_schedule_classifier_casia.txt --weight_decay 5e-5 --center_loss_factor 1e-2 --center_loss_alfa 0.9

when epoch 40   ,the issue arise

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[90,1,1,1792]
	 [[Node: InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](InceptionResnetV1/Block8/add)]]
	 [[Node: avg/_1782 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_37613_avg", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

I hava check the path carefully,the path is right
Hope to get your help

**Comment by luckyboysmith** [comment]
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 46 Chunks of size 1376256 totalling 60.38MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1417728 totalling 1.35MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1439232 totalling 1.37MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1519104 totalling 1.45MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1761792 totalling 1.68MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 7 Chunks of size 1769472 totalling 11.81MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1918976 totalling 1.83MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2064384 totalling 1.97MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2293248 totalling 2.19MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 14 Chunks of size 2359296 totalling 31.50MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 2424832 totalling 2.31MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 29 Chunks of size 2752512 totalling 76.12MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 199 Chunks of size 2949120 totalling 559.69MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 3043840 totalling 2.90MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 3197952 totalling 3.05MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 148 Chunks of size 3329280 totalling 469.91MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 8 Chunks of size 3538944 totalling 27.00MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4008704 totalling 3.82MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 9 Chunks of size 4370944 totalling 37.52MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 4849664 totalling 4.62MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 17 Chunks of size 5806080 totalling 94.13MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 34 Chunks of size 5898240 totalling 191.25MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 6347520 totalling 6.05MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 6579456 totalling 6.27MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 8179200 totalling 7.80MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 6 Chunks of size 8847360 totalling 50.62MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 9185024 totalling 8.76MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 9987840 totalling 47.62MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 11888640 totalling 11.34MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 10 Chunks of size 19975680 totalling 190.50MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 31 Chunks of size 20643840 totalling 610.31MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 17 Chunks of size 26634240 totalling 431.81MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 27648000 totalling 26.37MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 33269760 totalling 31.73MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 35032320 totalling 33.41MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 41587200 totalling 198.30MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 49567744 totalling 47.27MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 53429760 totalling 50.95MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 2 Chunks of size 68302080 totalling 130.28MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 5 Chunks of size 71896320 totalling 342.83MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 87282176 totalling 83.24MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 89579520 totalling 341.72MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 133800960 totalling 127.60MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 135827456 totalling 129.54MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 4 Chunks of size 136604160 totalling 521.10MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 158172928 totalling 150.84MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 254048000 totalling 242.28MiB
I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 5.54GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  5951455232
InUse:                  5950830080
MaxInUse:               5951397632
NumAllocs:               726678842
MaxAllocSize:           1397393152

W tensorflow/core/common_runtime/bfc_allocator.cc:274] *****************x*********************************************************************************x
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 630.0KiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[90,1,1,1792]
Traceback (most recent call last):
  File "src/train_softmax.py", line 454, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 224, in main
    total_loss, train_op, summary_op, summary_writer, regularization_losses, args.learning_rate_schedule_file)
  File "src/train_softmax.py", line 295, in train
    err, _, step, reg_loss = sess.run([loss, train_op, global_step, regularization_losses], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[90,1,1,1792]
	 [[Node: InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](InceptionResnetV1/Block8/add)]]
	 [[Node: avg/_1782 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_37613_avg", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool', defined at:
  File "src/train_softmax.py", line 454, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/train_softmax.py", line 156, in main
    weight_decay=args.weight_decay)
  File "/home/wang/facenet-master/src/models/inception_resnet_v1.py", line 149, in inference
    dropout_keep_prob=keep_probability, bottleneck_layer_size=bottleneck_layer_size, reuse=reuse)
  File "/home/wang/facenet-master/src/models/inception_resnet_v1.py", line 230, in inception_resnet_v1
    scope='AvgPool_1a_8x8')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/layers/python/layers/layers.py", line 128, in avg_pool2d
    outputs = layer.apply(inputs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 303, in apply
    return self.__call__(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/base.py", line 273, in __call__
    outputs = self.call(inputs, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/layers/pooling.py", line 277, in call
    data_format=utils.convert_data_format(self.data_format, 4))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/nn_ops.py", line 1765, in avg_pool
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 50, in _avg_pool
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[90,1,1,1792]
	 [[Node: InceptionResnetV1/Logits/AvgPool_1a_8x8/AvgPool = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 1, 1, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](InceptionResnetV1/Block8/add)]]
	 [[Node: avg/_1782 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_37613_avg", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by luckyboysmith** [comment]
@davidsandberg

**Comment by luckyboysmith** [comment]
about the casia data
Total number of classes: 8537
Total number of examples: 426256

**Comment by luckyboysmith** [comment]
this is my run code


 python src/train_softmax.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir ~/data/casia-align --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir /home/david/datasets/lfw/lfw_mtcnnalign_160 --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file data/learning_rate_schedule_classifier_casia.txt --weight_decay 5e-5 --center_loss_factor 1e-2 --center_loss_alfa 0.9

**Comment by luckyboysmith** [comment]
this is my run code
CUDA_VISIBLE_DEVICES=1 python src/train_softmax.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir ~/data/casia-align --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir ~/datasets/lfw/lfw_mtcnnalign_160 --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file data/learning_rate_schedule_classifier_casia.txt --weight_decay 5e-5 --center_loss_factor 1e-2 --center_loss_alfa 0.9

**Comment by luckyboysmith** [comment]
the data i used is casia 
about the casia data
Total number of classes: 8537
Total number of examples: 426256


in order to solve the ResourceExhaustedError issue
i set batch_size from 90 to 80
and set epoch_size from 1000 to 1125
in order to make each epoch contains 90k images
but the result is puzzling
Runnning forward pass on LFW images
Accuracy: 0.93800+-0.003
Validation rate: 0.61733+-0.01340 @ FAR=0.00100

why the validation rate is so low? just 0.6?

**Comment by luckyboysmith** [comment]
i hope to get some help

**Comment by zhengge** [comment]
@luckyboysmith I had the ResourceExhaustedError issue too。 Did you have solved it？

**Comment by luckyboysmith** [comment]
@zhengge  
hi, you can try decrease bact_size and increase epoch number
good luck!

**Comment by zhengge** [comment]
@luckyboysmith thanks!
