### ISSUE TITLE
How to solve in win7？

### ISSUE THREAD

**Issue by wyc2015fq** [davidsandberg/facenet#407]
Traceback (most recent call last):
  File "E:\FaceCode_Github\facenet\facenet-master\facenet-master\src\align\align
_dataset_mtcnn.py", line 143, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "E:\FaceCode_Github\facenet\facenet-master\facenet-master\src\align\align
_dataset_mtcnn.py", line 46, in main
    facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
  File "E:\FaceCode_Github\facenet\facenet-master\facenet-master\src\facenet.py"
, line 501, in store_revision_info
    gitproc = Popen(['git', 'rev-parse', 'HEAD'], stdout = PIPE, cwd=src_path)
  File "D:\softWarePackAge\anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "D:\softWarePackAge\anaconda3\lib\subprocess.py", line 1224, in _execute_
child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

**Comment by AppleCoffee** [comment]
Have you solved the problem?

**Comment by ZZZZZch** [comment]
Have you solved the problem?

**Comment by davidsandberg** [comment]
Hi,
You can just comment out the call to 
facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
and it should work fine.
