### ISSUE TITLE
Align the LFW dataset problem

### ISSUE THREAD

**Issue by Victoria2333** [davidsandberg/facenet#408]
Hello,when i execute:
for N in {1..4}; do python src/align/align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25 & done
it ends like:
......
/home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw/Debra_Shank/Debra_Shank_0001.jpg
/home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw/David_Bisbal/David_Bisbal_0001.jpg
Total number of images: 13233
Number of successfully aligned images: 3332
but it cannot skip to the next commmand,and i open another console to try next step:
python src/validate_on_lfw.py ~/datasets/lfw/lfw_mtcnnpy_160 ~/models/facenet/20170512-110547,
it ends like:
Model directory: ./src/models/20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
Traceback (most recent call last):
  File "./src/validate_on_lfw.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "./src/validate_on_lfw.py", line 57, in main
    facenet.load_model(args.model)
  File "/home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/src/facenet.py", line 388, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1415, in import_meta_graph
    return _import_meta_graph_def(read_meta_graph_file(meta_graph_or_file))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1305, in _import_meta_graph_def
    importer.import_graph_def(meta_graph_def.graph_def, name="")
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 228, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'VariableV2'
I have no idea of the error...
Thanks a lot for your help!

**Comment by Victoria2333** [comment]
By the way,when i ctrl+c,it occurs:
Total number of images: 13233
Number of successfully aligned images: 3332
^C
[1]   Done                    python src/align/align_dataset_mtcnn.py /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25
[2]   Done                    python src/align/align_dataset_mtcnn.py /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25
[3]-  Done                    python src/align/align_dataset_mtcnn.py /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25
[4]+  Done                    python src/align/align_dataset_mtcnn.py /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/raw /home/han/Desktop/haq_project/facenet-face-cluster-chinese-whispers--master/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order --gpu_memory_fraction 0.25

**Comment by Victoria2333** [comment]
Thanks,anyway...
I change the command to:python src/align/align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order
and the number of successfully aligned images equals total number of images !

**Comment by Victoria2333** [comment]
Thanks,anyway...
I change the command to:python src/align/align_dataset_mtcnn.py ~/datasets/lfw/raw ~/datasets/lfw/lfw_mtcnnpy_160 --image_size 160 --margin 32 --random_order
and the number of successfully aligned images equals total number of images!And i run the test,it succeed!!!
