### ISSUE TITLE
The error is happend when the model is loading

### ISSUE THREAD

**Issue by Paleve** [davidsandberg/facenet#416]
Model directory: /home/zts/PycharmProjects/facenet/models/facenet/20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 57, in main
    facenet.load_model(args.model)
  File "/home/zts/PycharmProjects/facenet/src/facenet.py", line 388, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1526, in import_meta_graph
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 502, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 258, in import_graph_def
    op_def = op_dict[node.op]
KeyError: u'VariableV2'

**Comment by huaitingpp** [comment]
I have this problem before.It's about the tensorflow version.My tensorflow version is 0.12 before,then I update to 1.2,it has been solved,you can try.
