### ISSUE TITLE
train models.inception_resnet_v2 

### ISSUE THREAD

**Issue by VictoryDong** [davidsandberg/facenet#44]
hi,
when  run facenet_train.py to train inception_resnet_v2 ,I met this problem :
Traceback (most recent call last):
  File "facenet_train.py", line 339, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train.py", line 70, in main
    phase_train=phase_train_placeholder, weight_decay=args.weight_decay)
  File "/home/mqq/victorydong/source/face2/facenet/facenet/src/models/inception_resnet_v1.py", line 135, in inference
    dropout_keep_prob=keep_probability)
  File "/home/mqq/victorydong/source/face2/facenet/facenet/src/models/inception_resnet_v1.py", line 157, in inception_resnet_v1
    with tf.variable_scope(scope, 'InceptionResnetV1', [inputs], reuse=reuse):
  File "/home/mqq/anaconda2/lib/python2.7/contextlib.py", line 84, in helper
    return GeneratorContextManager(func(*args, **kwds))
TypeError: variable_scope() got multiple values for keyword argument 'reuse'

**Comment by davidsandberg** [comment]
Hi,
Sorry for the delayed response. I have done some updates to the repo and also fixed the problem with the inception_resnet_v2. For most of the training I have done lately I have used inception_resnet_v1 model and training it as a classifier. It seems to work very well and I get a LFW accuracy of 0.94 when trained on the Casia/Facescrub dataset.
