### ISSUE TITLE
Error while testing on LFW

### ISSUE THREAD

**Issue by sidgan** [davidsandberg/facenet#446]
I'm following the instructions in the wiki page (https://github.com/davidsandberg/facenet/wiki/Validate-on-LFW) but when I run the command `python3 src/validate_on_lfw.py    /joint_casia_facescrub/facenet/20170830-192732` I get the following error. The LFW images are 160x160x3. Instead of the inception architecture, I'm using the nn4 architecture that was supplied in the code itself, I have modified it to take an input size of 160x160x3 and produce an output of 128. The nn4 architecture is [here](https://gist.github.com/sidgan/e8d8d3fe2ceb686be867e3ca8cd5dca8).

```
python3 src/validate_on_lfw.py    /joint_casia_facescrub/facenet/20170830-192732
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID dcdb:00:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
W tensorflow/stream_executor/cuda/cuda_driver.cc:590] creating context when one is currently active; existing: 0x3588260
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 1 with properties:
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID f865:00:00.0
Total memory: 11.17GiB
Free memory: 11.11GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 0 and 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:777] Peer access not supported between device ordinals 1 and 0
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y N
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 1:   N Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: dcdb:00:00.0)
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:1) -> (device: 1, name: Tesla K80, pci bus id: f865:00:00.0)
Model directory: /joint_casia_facescrub/facenet/20170830-192732
Metagraph file: model-20170830-192732.meta
Checkpoint file: model-20170830-192732.ckpt-40190
Runnning forward pass on LFW images
W tensorflow/core/framework/op_kernel.cc:993] Failed precondition: Attempting to use uninitialized value conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage
	 [[Node: conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage)]]
Traceback (most recent call last):
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1022, in _do_call
    return fn(*args)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1004, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage
	 [[Node: conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage)]]
	 [[Node: embeddings/_835 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5663_embeddings", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 80, in main
    emb_array[start_index:end_index,:] = sess.run(embeddings, feed_dict=feed_dict)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage
	 [[Node: conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage)]]
	 [[Node: embeddings/_835 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5663_embeddings", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage/read', defined at:
  File "src/validate_on_lfw.py", line 113, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 57, in main
    facenet.load_model(args.model)
  File "/home/deepvision/tensorflow/davidnet/facenet/src/facenet.py", line 388, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file))
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1566, in import_meta_graph
    **kwargs)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/framework/meta_graph.py", line 498, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/framework/importer.py", line 288, in import_graph_def
    op_def=op_def)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/deepvision/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

FailedPreconditionError (see above for traceback): Attempting to use uninitialized value conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage
	 [[Node: conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage/read = Identity[T=DT_FLOAT, _class=["loc:@conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage"], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_7x7/batch_norm/conv1_7x7/batch_norm/moments/moments_1/mean/ExponentialMovingAverage)]]
	 [[Node: embeddings/_835 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_5663_embeddings", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
```

**Comment by davidsandberg** [comment]
Hi,
It looks like the mean and variance estimates for batch normalization are not updated correctly. This becomes easier if the slim batch norm is used instead.
