### ISSUE TITLE
Scipy failed to import

### ISSUE THREAD

**Issue by popkristina** [davidsandberg/facenet#474]
Hello,
I've been trying to run the align_dataset_mtcnn on the dataset, and I keep getting errors like this:

Traceback (most recent call last):
  File "C:/Users/Kiki/facenet/src/align/align_dataset_mtcnn.py", line 29, in <module>
    from scipy import misc
  File "C:\Python36\lib\site-packages\scipy\misc\__init__.py", line 53, in <module>
    from scipy.interpolate._pade import pade
  File "C:\Python36\lib\site-packages\scipy\interpolate\__init__.py", line 176, in <module>
    from .interpolate import *
  File "C:\Python36\lib\site-packages\scipy\interpolate\interpolate.py", line 20, in <module>
    import scipy.linalg
  File "C:\Python36\lib\site-packages\scipy\linalg\__init__.py", line 175, in <module>
    from .misc import *
  File "C:\Python36\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Python36\lib\site-packages\scipy\linalg\blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

So I checked many times and scipy is definitely installed.

**Comment by bsolomon1124** [comment]
Why is this closed?  `_fblas` is now `fblas` and this error is still occuring.
