### ISSUE TITLE
error  in  training

### ISSUE THREAD

**Issue by louielu1027** [davidsandberg/facenet#52]
Epoch: [0][999/1000]	Time 0.223	Loss 0.164
Epoch: [0][1000/1000]	Time 0.226	Loss 0.185
Runnning forward pass on LFW images
Traceback (most recent call last):
  File "facenet_train.py", line 298, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train.py", line 134, in main
    actual_issame, args.seed, 60, images_placeholder, phase_train_placeholder, embeddings, nrof_folds=args.lfw_nrof_folds)
  File "/home/dl1/LXX/facenet-master_new/src/lfw.py", line 33, in validate
    np.asarray(actual_issame), seed, nrof_folds=nrof_folds)
  File "/home/dl1/LXX/facenet-master_new/src/facenet.py", line 428, in calculate_roc
    folds = KFold(n=nrof_pairs, n_folds=nrof_folds, shuffle=True, random_state=seed)
  File "/home/dl1/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/cross_validation.py", line 326, in __init__
    super(KFold, self).__init__(n, n_folds, shuffle, random_state)
  File "/home/dl1/anaconda/envs/tensorflow/lib/python2.7/site-packages/sklearn/cross_validation.py", line 257, in __init__
    " than the number of samples: {1}.").format(n_folds, n))
ValueError: Cannot have number of folds n_folds=10 greater than the number of samples: 0.
(tensorflow)dl1@dl1-B85M-DS3H:~/LXX/facenet-master_new/src$

**Comment by louielu1027** [comment]
solved

**Comment by tphyhFighting** [comment]
Hi ,how to solve this problem?
