### ISSUE TITLE
ValueError: The number of classes has to be greater than one; got 1

### ISSUE THREAD

**Issue by NathanielNguyen11** [davidsandberg/facenet#553]
Dear Mr/Ms.

Firstly, I strongly appreciate your work, From the latter I can gain a lot of knowledge about face recognition.
Secondly, Suppose that  I had 70 own images (my photos), then I try to train them for verifying my face purpose. Besides, I also used FLW and Casia pre_trained model, but they did not work. Hopefully, Someone can help me out.

![screenshot from 2017-11-27 13-05-04](https://user-images.githubusercontent.com/32150689/33250403-9dc8300c-d373-11e7-96b5-98f59d8bb049.png)

**Comment by MaartenBloemen** [comment]
You just need a 2nd class, you can't train an SVM classifier with just 1 class cause that would defeat the purpose of SVM. An easy way around this is to add an "Unknown" class which you fill with random faces.

**Comment by NathanielNguyen11** [comment]
Thank for your suggestion, It's very useful with me.
@MaartenBloemen

**Comment by mukulRustagi** [comment]
Hi, I got the same error 

```
  File "/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_search.py", line 639, in fit
    cv.split(X, y, groups)))
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 779, in __call__
    while self.dispatch_one_batch(iterator):
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 625, in dispatch_one_batch
    self._dispatch(tasks)
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 588, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 111, in apply_async
    result = ImmediateResult(func)
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 332, in __init__
    self.results = batch()
  File "/anaconda2/lib/python2.7/site-packages/sklearn/externals/joblib/parallel.py", line 131, in __call__
    return [func(*args, **kwargs) for func, args, kwargs in self.items]
  File "/anaconda2/lib/python2.7/site-packages/sklearn/model_selection/_validation.py", line 458, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/anaconda2/lib/python2.7/site-packages/sklearn/svm/base.py", line 150, in fit
    y = self._validate_targets(y)
  File "/anaconda2/lib/python2.7/site-packages/sklearn/svm/base.py", line 506, in _validate_targets
    % len(cls))
ValueError: The number of classes has to be greater than one; got 1
```
**I am not able to figure out which class it is talking about. So,can you tell me where should that "unknown" class.**

**Comment by Prateek830** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-55-b215bb7db201> in <module>()
      1 model=svm.SVC(kernel='linear')
----> 2 model.fit(ingredients, type_label)

/home/prateek/.local/lib/python2.7/site-packages/sklearn/svm/base.pyc in fit(self, X, y, sample_weight)
    148 
    149         X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr')
--> 150         y = self._validate_targets(y)
    151 
    152         sample_weight = np.asarray([]

/home/prateek/.local/lib/python2.7/site-packages/sklearn/svm/base.pyc in _validate_targets(self, y)
    504             raise ValueError(
    505                 "The number of classes has to be greater than one; got %d"
--> 506                 % len(cls))
    507 
    508         self.classes_ = cls

ValueError: The number of classes has to be greater than one; got 1
![Screenshot from 2019-03-09 10-16-03](https://user-images.githubusercontent.com/45484891/54066353-73dc1500-4254-11e9-9f84-a909b4ebecf4.png)

I got too the same error, which unknown class should i add it .
​

**Comment by umeshhello12** [comment]
![ddd](https://user-images.githubusercontent.com/43229966/62699321-e36d5080-b9fc-11e9-8bad-b906d54694fe.JPG)
The number of classes has to be greater than one; got 1 class
Please help me sir

**Comment by fagnermacedo** [comment]
To fix, you need to do this.

y_train = y_train.astype(np.int8)

**Comment by JayavarshiniRaja** [comment]
> ValueError Traceback (most recent call last) in () 1 model=svm.SVC(kernel='linear') ----> 2 model.fit(ingredients, type_label)
> 
> /home/prateek/.local/lib/python2.7/site-packages/sklearn/svm/base.pyc in fit(self, X, y, sample_weight) 148 149 X, y = check_X_y(X, y, dtype=np.float64, order='C', accept_sparse='csr') --> 150 y = self._validate_targets(y) 151 152 sample_weight = np.asarray([]
> 
> /home/prateek/.local/lib/python2.7/site-packages/sklearn/svm/base.pyc in _validate_targets(self, y) 504 raise ValueError( 505 "The number of classes has to be greater than one; got %d" --> 506 % len(cls)) 507 508 self.classes_ = cls
> 
> ValueError: The number of classes has to be greater than one; got 1 ![Screenshot from 2019-03-09 10-16-03](https://user-images.githubusercontent.com/45484891/54066353-73dc1500-4254-11e9-9f84-a909b4ebecf4.png)
> 
> I got too the same error, which unknown class should i add it . ​

did you solved this error
