### ISSUE TITLE
align_dataset_mtcnn.py using fail

### ISSUE THREAD

**Issue by situjie68** [davidsandberg/facenet#604]
Anyone who can help me?

    After getting the data LFW(put in facenet/data/lfw/raw), I want to handle these data using align_dataset_mtcnn.py, but something wrong happened. 
   My command is "cd facenet     export PYTHONPATH=$(pwd)/src                                                         python ./src/align/align_dataset_mtcnn.py ./data/lfw/raw ./data/lfw/lfw_160 --image_size 160 --margin 32 --random_order" (MAC without GPU)

   Error as below:
   Traceback (most recent call last):
  File "./src/align/align_dataset_mtcnn.py", line 35, in <module>
    import align.detect_face
  File "/Users/tongwenjie/Desktop/twj/TensorFlow项目及代码/Face recognition/davidsandberg_facenet_3k/facenet/src/align/detect_face.py", line 34, in <module>
    import cv2
  File "/Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/cv2.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib
192:facenet tongwenjie$ python ./src/align/align_dataset_mtcnn.py ./data/lfw/raw ./data/lfw/lfw_160 --image_size 160 --margin 32
Traceback (most recent call last):
  File "./src/align/align_dataset_mtcnn.py", line 35, in <module>
    import align.detect_face
  File "/Users/tongwenjie/Desktop/twj/TensorFlow项目及代码/Face recognition/davidsandberg_facenet_3k/facenet/src/align/detect_face.py", line 34, in <module>
    import cv2
  File "/Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/__init__.py", line 4, in <module>
    from .cv2 import *
ImportError: dlopen(/Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/cv2.so, 2): Symbol not found: _clock_gettime
  Referenced from: /Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib

**Comment by jarski** [comment]
"Referenced from: /Users/tongwenjie/anaconda2/lib/python2.7/site-packages/cv2/.dylibs/libavutil.55.78.100.dylib (which was built for Mac OS X 10.12)"

Try to upgrade to Mac OS X 10.12 or later.

**Comment by situjie68** [comment]
@jarski  thanks for you advice.
