### ISSUE TITLE
Use compare.py ERROR:

### ISSUE THREAD

**Issue by mengxiabing** [davidsandberg/facenet#674]
D:\ai\facenet-master>python src\compare.py models\facenet\20170512-110547 data\i
mages\001.jpg data\images\002.jpg
Creating networks and loading parameters
2018-03-28 11:07:23.951266: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructi
ons that this TensorFlow binary was not compiled to use: AVX2
2018-03-28 11:07:24.337288: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with pro
perties:
name: GeForce 840M major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 2.00GiB freeMemory: 1.93GiB
2018-03-28 11:07:24.337288: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devi
ces: 0
2018-03-28 11:07:28.411521: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow devi
ce (/job:localhost/replica:0/task:0/device:GPU:0 with 2048 MB memory) -> physica
l GPU (device: 0, name: GeForce 840M, pci bus id: 0000:01:00.0, compute capabili
ty: 5.0)
2018-03-28 11:07:28.413521: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\stream_executor\cuda\cuda_driver.cc:936] failed to allocate 2.00G (
2147483648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
WARNING:tensorflow:From D:\ai\facenet-master\src\align\detect_face.py:210: calli
ng reduce_max (from tensorflow.python.ops.math_ops) with keep_dims is deprecated
 and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
WARNING:tensorflow:From D:\ai\facenet-master\src\align\detect_face.py:212: calli
ng reduce_sum (from tensorflow.python.ops.math_ops) with keep_dims is deprecated
 and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2018-03-28 11:07:32.816773: E C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\stream_executor\cuda\cuda_blas.cc:443] failed to create cublas hand
le: CUBLAS_STATUS_NOT_INITIALIZED
2018-03-28 11:07:32.937780: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\3
5\tensorflow\stream_executor\stream.cc:1901] attempting to perform BLAS operatio
n using StreamExecutor without BLAS support
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 1361, in _do_call
    return fn(*args)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed
: m=4900, n=4, k=32
         [[Node: pnet/conv4-2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", di
lations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=tru
e, _device="/job:localhost/replica:0/task:0/device:GPU:0"](pnet/PReLU3/add, pnet
/conv4-2/weights/read)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\compare.py", line 129, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src\compare.py", line 40, in main
    images = load_and_align_data(args.image_files, args.image_size, args.margin,
 args.gpu_memory_fraction)
  File "src\compare.py", line 96, in load_and_align_data
    bounding_boxes, _ = align.detect_face.detect_face(img, minsize, pnet, rnet,
onet, threshold, factor)
  File "D:\ai\facenet-master\src\align\detect_face.py", line 329, in detect_face

    out = pnet(img_y)
  File "D:\ai\facenet-master\src\align\detect_face.py", line 293, in <lambda>
    pnet_fun = lambda img : sess.run(('pnet/conv4-2/BiasAdd:0', 'pnet/prob1:0'),
 feed_dict={'pnet/input:0':img})
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 905, in run
    run_metadata_ptr)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 1355, in _do_run
    options, run_metadata)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\client\se
ssion.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed
: m=4900, n=4, k=32
         [[Node: pnet/conv4-2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", di
lations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=tru
e, _device="/job:localhost/replica:0/task:0/device:GPU:0"](pnet/PReLU3/add, pnet
/conv4-2/weights/read)]]

Caused by op 'pnet/conv4-2/Conv2D', defined at:
  File "src\compare.py", line 129, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src\compare.py", line 40, in main
    images = load_and_align_data(args.image_files, args.image_size, args.margin,
 args.gpu_memory_fraction)
  File "src\compare.py", line 89, in load_and_align_data
    pnet, rnet, onet = align.detect_face.create_mtcnn(sess, None)
  File "D:\ai\facenet-master\src\align\detect_face.py", line 282, in create_mtcn
n
    pnet = PNet({'data':data})
  File "D:\ai\facenet-master\src\align\detect_face.py", line 73, in __init__
    self.setup()
  File "D:\ai\facenet-master\src\align\detect_face.py", line 230, in setup
    .conv(1, 1, 4, 1, 1, relu=False, name='conv4-2'))
  File "D:\ai\facenet-master\src\align\detect_face.py", line 51, in layer_decora
ted
    layer_output = op(self, layer_input, *args, **kwargs)
  File "D:\ai\facenet-master\src\align\detect_face.py", line 156, in conv
    output = convolve(inp, kernel)
  File "D:\ai\facenet-master\src\align\detect_face.py", line 152, in <lambda>
    convolve = lambda i, k: tf.nn.conv2d(i, k, [1, s_h, s_w, 1], padding=padding
)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_n
n_ops.py", line 717, in conv2d
    data_format=data_format, dilations=dilations, name=name)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\ops.py", line 3271, in create_op
    op_def=op_def)
  File "D:\Program Files\Anaconda3\lib\site-packages\tensorflow\python\framework
\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-
access

InternalError (see above for traceback): Blas SGEMM launch failed : m=4900, n=4,
 k=32
         [[Node: pnet/conv4-2/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", di
lations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=tru
e, _device="/job:localhost/replica:0/task:0/device:GPU:0"](pnet/PReLU3/add, pnet
/conv4-2/weights/read)]]

**Comment by vaibhav0195** [comment]
Hey @mengxiabing  
how did you fixed the error ?
I am getting the same error

Thanks in advance :)
