### ISSUE TITLE
run facenet on jetson tx2 error

### ISSUE THREAD

**Issue by airukongqi** [davidsandberg/facenet#679]
HI:
I want use tx2 to do face recognition with facenet.
Copy the trianed model and classifier from the pc to the tx2.
And install tensorflow(1.5),and others stuff
Run the contributed/real_time_face_recognition.py
Then report errors:
Model directory: /home/nvidia/facenet/facenet/contributed/../src/models/20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000

WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
Traceback (most recent call last):
File "contributed/real_time_face_recognition.py", line 107, in <module>
main(parse_arguments(sys.argv[1:]))
File "contributed/real_time_face_recognition.py", line 63, in main
face_recognition = face.Recognition()
File "/home/nvidia/facenet/facenet/contributed/face.py", line 65, in __init__
self.identifier = Identifier()
File "/home/nvidia/facenet/facenet/contributed/face.py", line 91, in __init__
self.model, self.class_names = pickle.load(infile)
File "/usr/lib/python2.7/pickle.py", line 1384, in load
return Unpickler(file).load()
File "/usr/lib/python2.7/pickle.py", line 864, in load
dispatch[key](self)
File "/usr/lib/python2.7/pickle.py", line 892, in load_proto
raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3

I tested it on the PC,and it's ok. the tensorflow version on pc is 1.6, and the tx2 tensorflow version is 1.5.

**Comment by davidsandberg** [comment]
Maybe you can get some ideas from here: https://stackoverflow.com/questions/25843698/valueerror-unsupported-pickle-protocol-3-python2-pickle-can-not-load-the-file

**Comment by nanhui69** [comment]
@airukongqi can you deploy your it into tx2  successful?
