### ISSUE TITLE
Error while running ./contributed/clustering.py

### ISSUE THREAD

**Issue by buddhashrestha** [davidsandberg/facenet#680]
I wanted to cluster my images. It worked using ./contributed/cluster.py, but while doing so using the chinese whisper algorithm ( ./contributed/clustering.py), I got the following error:

Traceback (most recent call last):                                                                                                                                   [5/440]
  File "./contributed/clustering.py", line 268, in <module>
    main(parse_args())
  File "./contributed/clustering.py", line 242, in main
    sorted_clusters = cluster_facial_encodings(facial_encodings)
  File "./contributed/clustering.py", line 150, in cluster_facial_encodings
    sorted_clusters = _chinese_whispers(facial_encodings.items())
  File "./contributed/clustering.py", line 89, in _chinese_whispers
    shuffle(cluster_nodes)
  File "/usr/lib/python2.7/random.py", line 293, in shuffle
    x[i], x[j] = x[j], x[i]
TypeError: 'NodeView' object does not support item assignment

It seems that it occurred when trying to call the shuffle function.

**Comment by buddhashrestha** [comment]
Ok figured it out. 
change from `shuffle(cluster_nodes)` to `shuffle(list(cluster_nodes))`
