### ISSUE TITLE
facenet_train_classifier.py Invalid PNG header (never returns from sess.run(...))

### ISSUE THREAD

**Issue by Jusya** [davidsandberg/facenet#75]
I was trying to train model with facenet_train_classifier.py but faced some troubles. After graph is initialized the tf.train.start_queue_runners(sess=sess) method is called I get these mistakes on different threads:

```
ERROR:tensorflow:Exception in QueueRunner: Invalid PNG header, data size 11796
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile)]]
Caused by op 'DecodePng', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

Exception in thread Thread-10:
Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _do_call
    return fn(*args)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 947, in _run_fn
    status, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 11796
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/queue_runner.py", line 187, in _run
    sess.run(enqueue_op)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 11796
	 [[Node: DecodePng = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile)]]
Caused by op 'DecodePng', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()


ERROR:tensorflow:Exception in QueueRunner: Invalid PNG header, data size 16993
	 [[Node: DecodePng_2 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_2)]]
Caused by op 'DecodePng_2', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

Exception in thread Thread-12:
Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _do_call
    return fn(*args)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 947, in _run_fn
    status, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 16993
	 [[Node: DecodePng_2 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/queue_runner.py", line 187, in _run
    sess.run(enqueue_op)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 16993
	 [[Node: DecodePng_2 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_2)]]
Caused by op 'DecodePng_2', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()


ERROR:tensorflow:Exception in QueueRunner: Invalid PNG header, data size 17687
	 [[Node: DecodePng_3 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_3)]]
Caused by op 'DecodePng_3', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _do_call
    return fn(*args)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 947, in _run_fn
    status, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 17687
	 [[Node: DecodePng_3 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_3)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/queue_runner.py", line 187, in _run
    sess.run(enqueue_op)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 17687
	 [[Node: DecodePng_3 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_3)]]
Caused by op 'DecodePng_3', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()


ERROR:tensorflow:Exception in QueueRunner: Invalid PNG header, data size 17122
	 [[Node: DecodePng_1 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_1)]]
Caused by op 'DecodePng_1', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()

Exception in thread Thread-11:
Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 965, in _do_call
    return fn(*args)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 947, in _run_fn
    status, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors.py", line 450, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 17122
	 [[Node: DecodePng_1 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_1)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/ysavelyeva/anaconda3/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/training/queue_runner.py", line 187, in _run
    sess.run(enqueue_op)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 710, in run
    run_metadata_ptr)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 908, in _run
    feed_dict_string, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 958, in _do_run
    target_list, options, run_metadata)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 978, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: Invalid PNG header, data size 17122
	 [[Node: DecodePng_1 = DecodePng[channels=3, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/cpu:0"](ReadFile_1)]]
Caused by op 'DecodePng_1', defined at:
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 324, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 123, in read_and_augument_data
    image, label = read_images_from_disk(input_queue)
  File "/home/ysavelyeva/Documents/Projects/facenet-master/src/facenet.py", line 108, in read_images_from_disk
    example = tf.image.decode_png(file_contents, channels=3)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_image_ops.py", line 317, in decode_png
    channels=channels, dtype=dtype, name=name)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2317, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ysavelyeva/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1239, in __init__
    self._traceback = _extract_stack()
```

But then it returns from  tf.train.start_queue_runners method without crashing the program and continues to work until the first forward pass. After sess.run() is entered it never returned.

First, I thought, that it is a problem with images, because I've tried to train on small part of vgg dataset (and maybe some png were corrupted, because I made a hard stops of downloading it for several times), but then I've tried to train it on lfw, with which validation code seems to be working good (so it is not corrupted), and I had the same errors.

Do you have any ideas, why I have such errors?

Waiting for you apply, thank you in advance)

**Comment by davidsandberg** [comment]
Hi,
The reason why sess.run(...) never returns is probably because the input buffers are empty. And the the buffers are empty because tensorflows PNG decoder fails to decode the images. So I think you should continue to look into the images in your dataset.
For example validate_on_lfw.py uses a different way of reading images (i.e. scipy instead of TFs PNG decoder). Could it for example be that you are using jpg files with png extension and that TFs PNG decoder doesn't realize that but scipy does?

**Comment by Jusya** [comment]
There was problem with downloading vgg dataset, some of downloaded files had .err extension, removing them from all folders in vgg dataset solved the problem.

Thank you for your answer!)
