### ISSUE TITLE
problem with Pre-trained model VGG2.

### ISSUE THREAD

**Issue by rashmisgh** [davidsandberg/facenet#753]
Hey, I am facing this issue when using the pre-trained model of VGG2.
/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Loading model...
2018-05-19 18:45:58.151132: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-19 18:45:58.151162: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-19 18:45:58.151166: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-05-19 18:45:58.151185: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-05-19 18:45:58.151189: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1039, in _do_call
    return fn(*args)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1021, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_18 = Assign[T=DT_FLOAT, _class=["loc:@InceptionResnetV1/Bottleneck/BatchNorm/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](InceptionResnetV1/Bottleneck/BatchNorm/beta, save/RestoreV2_18)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "temp_img1.py", line 163, in <module>
    extract_feature = FaceFeature(FRGraph)
  File "/home/anju/rashmi_folder/FaceRec_old_before_24Apr_2018/face_feature.py", line 25, in __init__
    saver.restore(self.sess, model_path)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1457, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 778, in run
    run_metadata_ptr)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 982, in _run
    feed_dict_string, options, run_metadata)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1032, in _do_run
    target_list, options, run_metadata)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1052, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_18 = Assign[T=DT_FLOAT, _class=["loc:@InceptionResnetV1/Bottleneck/BatchNorm/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](InceptionResnetV1/Bottleneck/BatchNorm/beta, save/RestoreV2_18)]]

Caused by op 'save/Assign_18', defined at:
  File "temp_img1.py", line 163, in <module>
    extract_feature = FaceFeature(FRGraph)
  File "/home/anju/rashmi_folder/FaceRec_old_before_24Apr_2018/face_feature.py", line 24, in __init__
    saver = tf.train.Saver() #saver load pretrain model
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/ops/state_ops.py", line 270, in assign
    validate_shape=validate_shape)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/anju/.virtualenvs/dl4cv2/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [128] rhs shape= [512]
	 [[Node: save/Assign_18 = Assign[T=DT_FLOAT, _class=["loc:@InceptionResnetV1/Bottleneck/BatchNorm/beta"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](InceptionResnetV1/Bottleneck/BatchNorm/beta, save/RestoreV2_18)]]

Please help me with this.

**Comment by Sherry40931** [comment]
The embedding size of pre-trained model trained on VGGFace2 is 512, but looks like you are trying to use 128, so the shape is not matched. 

You can change the embedding size to 512 as the original pre-trained model or train your model with 128 embeddings size on the VGGFace2 from scratch.

**Comment by rashmisgh** [comment]
Where is this 128 embedding declared?

**Comment by Sherry40931** [comment]
Just add `--embedding_size 128` to your command, or modify it in the `parse_arguments`

**Comment by rashmisgh** [comment]
Will this work with Mtcnn face detection because I am using this weights
for this repo :- http://github.com/vudung45/FaceRec

**Comment by Sherry40931** [comment]
I see, you are running face_feature.py, right? If so, you need to add `bottleneck_layer_size=512` when you inference the network. To be more specific, on line 22 of the script face_feature.py,

change this:
`resnet.inference(self.x, 0.6, phase_train=False)`

to this:
`resnet.inference(self.x, 0.6, bottleneck_layer_size=512, phase_train=False)`

and I think the pre-trained model could be loaded.

**Comment by rashmisgh** [comment]
Thanks a lot.

**Comment by rashmisgh** [comment]
@Sherry40931 sorry to bother you again but please help me, I am trying to detect side face using Mtcnn but the problem that the side faces are not getting detected. what is the argument I can fine tune to solve this problem? or any method to add a layer to this so that side face can be detected.

**Comment by Sherry40931** [comment]
The problem of side face not getting detected is related to MTCNN but not faceNet. So neither fine-tuning nor adding a layer could solve the problem.

Although MTCNN is not perfect, it is robust enough to detect profile face from my experiment. I assume that you are using the FaceRec repo for detection in your project and I suggest you to take a look at the implementation of it. It might be different from davidsandberg's repo thus leads to inferior performance. You can also try other face detection algorithm as well.

**Comment by hungnv21292** [comment]
hi @Sherry40931 

Where can download pre-trained model with embedding_size = 128?

Thanks

**Comment by Sherry40931** [comment]
> hi @Sherry40931
> 
> Where can download pre-trained model with embedding_size = 128?
> 
> Thanks

You can use the old model from the [readme history](https://github.com/davidsandberg/facenet/blob/529c3b0b5fc8da4e0f48d2818906120f2e5687e6/README.md):
There were two model listed in the table.
