### ISSUE TITLE
OutOfRangeError after 50 epochs

### ISSUE THREAD

**Issue by llj098** [davidsandberg/facenet#84]
Hi, 

I trained the model by the instruction at https://github.com/davidsandberg/facenet/wiki/Classifier-training-of-inception-resnet-v1 , but after 50 epochs, the training program crashed. Below are the traceback:

```
Traceback (most recent call last):
  File "facenet_train_classifier.py", line 345, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 173, in main
    update_centers)
  File "facenet_train_classifier.py", line 201, in train
    err, _, _, step, reg_loss = sess.run([loss, train_op, update_centers, global_step, regularization_losses], feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.OutOfRangeError: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]

Caused by op u'batch_join', defined at:
  File "facenet_train_classifier.py", line 345, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "facenet_train_classifier.py", line 85, in main
    args.batch_size, args.max_nrof_epochs, args.random_crop, args.random_flip, args.nrof_preprocess_threads)
  File "/home/liulijin/old/home/liulijin/facenet/src/facenet.py", line 138, in read_and_augument_data
    allow_smaller_final_batch=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/input.py", line 708, in batch_join
    dequeued = queue.dequeue_up_to(batch_size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 499, in dequeue_up_to
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 951, in _queue_dequeue_up_to
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
```

OS: ubuntu 16.04
Tensorflow: 0.11
CUDA: 8.0
facenet version: e5d852a3eb7a080f0a8006d281d6d9175200a614

I am new to tensorflow/ML, is it a bug or I did something wrong?

Thanks in advance!

**Comment by davidsandberg** [comment]
What was the command line you used when you ran the training? Did you set the parameter max_nrof_epochs to 50? If that is the case I also ran into this but somehow forgot to fix it. It is caused by the slice_input_producer reaching it's epoch limit a little bit before training stops. It's not a serious problem and doesn't affect the result but the easiest fix is to num_epochs=None in the call to slice_input_producer.

**Comment by llj098** [comment]
@davidsandberg thanks for your response, my command line is: 

` python facenet_train_classifier.py --logs_base_dir ~/logs/facenet/ --models_base_dir ~/models/facenet/ --data_dir ~/facenet/data/train_test/facescrub_mtcnnalign_182_160 --image_size 160 --model_def models.inception_resnet_v1 --lfw_dir ~/facenet/data/lfw_mtcnnpy_160 --weight_decay 2e-4 --optimizer RMSPROP --learning_rate -1 --max_nrof_epochs 80 --keep_probability 0.8 --random_crop --random_flip --learning_rate_schedule_file ../data/learning_rate_schedule_classifier_long.txt --center_loss_factor 2e-4`

So, my `max_nrof_epochs` is set to **80** NOT **50**, is this a different case ?

Plus, before crash, I got a lot for warniing log:

```
W tensorflow/core/framework/op_kernel.cc:968] Out of range: Reached limit of 80
         [[Node: input_producer/input_producer/fraction_of_32_full/limit_epochs/CountUpTo = CountUpTo[T=DT_INT64, _class=["loc:@input_producer/input_producer/fraction_of_32_full/
limit_epochs/epochs"], limit=80, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/limit_epochs/epochs)]]
Epoch: [50][510/1000]   Time 0.462      Loss 1.861      RegLoss 1.590
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
         [[Node: input_producer/fraction_of_32_full_Dequeue = QueueDequeue[_class=["loc:@input_producer/input_producer/fraction_of_32_full/fraction_of_32_full"], component_types=
[DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](input_producer/input_producer/fraction_of_32_full/fraction_of_32_full)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_0_input_producer/input_producer/fraction_of_32_full/fraction_of_32_full' is closed and has insufficient el
ements (requested 1, current size 0)
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
W tensorflow/core/framework/op_kernel.cc:968] Out of range: FIFOQueue '_1_batch_join/fifo_queue' is closed and has insufficient elements (requested 90, current size 0)
         [[Node: batch_join = QueueDequeueUpTo[_class=["loc:@batch_join/fifo_queue"], component_types=[DT_FLOAT, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:
0/cpu:0"](batch_join/fifo_queue, batch_join/n)]]
....


```

**Comment by llj098** [comment]
I set num_epochs=None in the call slice_input_produce, problem solved.

Thanks!
