### ISSUE TITLE
AttributeError: module 'facenet' has no attribute 'store_revision_info'

### ISSUE THREAD

**Issue by shendrysu** [davidsandberg/facenet#843]
hi, I run  C:\Users\shend\Anaconda3>python c:\facenet\src\align\align_dataset_mtcnn.py c:\lfw c:\imagenes

but a I have this error:

Traceback (most recent call last):
  File "c:\facenet\src\align\align_dataset_mtcnn.py", line 160, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "c:\facenet\src\align\align_dataset_mtcnn.py", line 47, in main
    facenet.store_revision_info(src_path, output_dir, ' '.join(sys.argv))
AttributeError: module 'facenet' has no attribute 'store_revision_info'
 what's wrong with de facenet code?

**Comment by xiaohuahao** [comment]
import facenet.src.facenet as facenet
this can help you.

**Comment by shendrysu** [comment]
thank you
