### ISSUE TITLE
validate_on_lfw.py: No op named DecodeBmp in defined operations

### ISSUE THREAD

**Issue by AnkitaBeniwal** [davidsandberg/facenet#855]
I am having a similar issue. Heres the error
Model directory: /home/ankita/models/facenet/20180402-114759
Metagraph file: model-20180402-114759.meta
Checkpoint file: model-20180402-114759.ckpt-275
Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 164, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 73, in main
    facenet.load_model(args.model, input_map=input_map)
  File "/home/ankita/image/face_detector/Others/facenet/src/facenet.py", line 381, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
  File "/home/ankita/image/face_detector/Others/facenet/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/home/ankita/image/face_detector/Others/facenet/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/ankita/image/face_detector/Others/facenet/lib/python3.6/site-packages/tensorflow/python/framework/importer.py", line 283, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named DecodeBmp in defined operations.

Any help

**Comment by AnkitaBeniwal** [comment]
I had the tensorflow mismatch. I had installed 1.2.0 while it needed 1.3.0. Thanks @nonameever95 for mentioning it in your issues.

**Comment by nonameever95** [comment]
Glad I helped 👍

**Comment by Edward-Jone** [comment]
thank you , you have sloved my problem perfectly!!!
