### ISSUE TITLE
ValueError: Attempted to map inputs that were not found in graph_def: [label_batch:0]

### ISSUE THREAD

**Issue by DDDoriM1** [davidsandberg/facenet#900]
HI,  @davidsandberg , I'm trying to use facenet in my computer. But when I tried to verify that the environment is well matched. I got the ValueError. Whatever I use Windows 10 or Ubuntu 16.04, I got the same error. Sorry about my poor English, thanks.

Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 168, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 77, in main
    facenet.load_model(args.model, input_map=input_map)
  File "/home/yangziyuan/facenet/src/facenet.py", line 380, in load_model
    tf.import_graph_def(graph_def, input_map=input_map, name='')
  File "/home/yangziyuan/anaconda2/envs/yang/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 432, in new_func
    return func(*args, **kwargs)
  File "/home/yangziyuan/anaconda2/envs/yang/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 777, in import_graph_def
    % ', '.join(absent_input_keys))
ValueError: Attempted to map inputs that were not found in graph_def: [label_batch:0]

validate_on_lfw.py
```

def main(args):
  
    with tf.Graph().as_default():
      
        with tf.Session() as sess:
            
            # Read the file containing the pairs used for testing
            pairs = lfw.read_pairs(os.path.expanduser(args.lfw_pairs))

            # Get the paths for the corresponding images
            paths, actual_issame = lfw.get_paths(os.path.expanduser(args.lfw_dir), pairs)
            
            image_paths_placeholder = tf.placeholder(tf.string, shape=(None,1), name='image_paths')
            labels_placeholder = tf.placeholder(tf.int32, shape=(None,1), name='labels')
            batch_size_placeholder = tf.placeholder(tf.int32, name='batch_size')
            control_placeholder = tf.placeholder(tf.int32, shape=(None,1), name='control')
            phase_train_placeholder = tf.placeholder(tf.bool, name='phase_train')
 
            nrof_preprocess_threads = 4
            image_size = (args.image_size, args.image_size)
            eval_input_queue = data_flow_ops.FIFOQueue(capacity=2000000,
                                        dtypes=[tf.string, tf.int32, tf.int32],
                                        shapes=[(1,), (1,), (1,)],
                                        shared_name=None, name=None)
            eval_enqueue_op = eval_input_queue.enqueue_many([image_paths_placeholder, labels_placeholder, control_placeholder], name='eval_enqueue_op')
            image_batch, label_batch = facenet.create_input_pipeline(eval_input_queue, image_size, nrof_preprocess_threads, batch_size_placeholder)
     
            # Load the model
            input_map = {'label_batch': label_batch,'image_batch': image_batch, 'phase_train': phase_train_placeholder}
            facenet.load_model(args.model, input_map=input_map)

            # Get output tensor
            embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
#              
            coord = tf.train.Coordinator()
            tf.train.start_queue_runners(coord=coord, sess=sess)

            evaluate(sess, eval_enqueue_op, image_paths_placeholder, labels_placeholder, phase_train_placeholder, batch_size_placeholder, control_placeholder,
                embeddings, label_batch, paths, actual_issame, args.lfw_batch_size, args.lfw_nrof_folds, args.distance_metric, args.subtract_mean,
                args.use_flipped_images, args.use_fixed_image_standardization)
```

facenet.py
```
def load_model(model, input_map=None):
    # Check if the model is a model directory (containing a metagraph and a checkpoint file)
    #  or if it is a protobuf file with a frozen graph
    model_exp = os.path.expanduser(model)
    if (os.path.isfile(model_exp)):
        print('Model filename: %s' % model_exp)
        with gfile.FastGFile(model_exp,'rb') as f:
            graph_def = tf.GraphDef()
            graph_def.ParseFromString(f.read())
            #tf.import_graph_def(graph_def,name='')
            #######################################
            #############Here            ###########
            #######################################
            
            print('\n\n\nthe input_map is :%s\n\n\n'%input_map)
            tf.import_graph_def(graph_def, input_map=input_map, name='')
    else:
        print('Model directory: %s' % model_exp)
        meta_file, ckpt_file = get_model_filenames(model_exp)
        
        print('Metagraph file: %s' % meta_file)
        print('Checkpoint file: %s' % ckpt_file)
      
        saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
        saver.restore(tf.get_default_session(), os.path.join(model_exp, ckpt_file))
    
```

**Comment by wmmbjut** [comment]
想问一下你解决这个问题了吗，我 最近也在跑facenet，也遇到了这个问题，和你的一样一样的。

**Comment by DDDoriM1** [comment]
>           想问一下你解决这个问题了吗，我 最近也在跑facenet，也遇到了这个问题，和你的一样一样的。
不好意思，并没有。。不知道是哪儿错了。我之前其实在windows上跑通过，过了俩礼拜就不知道怎么就跑不通了，然后重新弄不管是windows还是linux都跑不了都是报一样的错误。。哎。。

**Comment by wmmbjut** [comment]
那你有自己重新训练过吗，我只跑通了train_softmax,但是准确率一直在0.5左右，而且并不上升。train_triplelpss这个也遇到了问题没有跑通，想问一下你有成功训练过自己的模型吗

**Comment by Salary-only-17k** [comment]
@davidsandberg cannot understand chinese,.....haha, using your poor english is more helpful.

**Comment by DDDoriM1** [comment]
>           那你有自己重新训练过吗，我只跑通了train_softmax,但是准确率一直在0.5左右，而且并不上升。train_triplelpss这个也遇到了问题没有跑通，想问一下你有成功训练过自己的模型吗

我没有自己重新训练过昂，我用的是它训练好的模型20170512-110547的那个

**Comment by DDDoriM1** [comment]
I could run the facenet one week ago, but it can not work now whatever the os is windows or ubuntu. That is so confused. I tried to reconfigure the environment, then I got the ValueError in windows and ubuntu.

**Comment by wmmbjut** [comment]
这个问题解决了，我觉得就是版本的问题，你别用这个模型，去github上下载他最新的那个模型，2018的那个，就不出错了，我用这个运行之后就输出准确率什么的了。虽然还有点别的小错误，但大体已经可以了。我刚跑出来，你可以试试。

**Comment by DDDoriM1** [comment]
> 这个问题解决了，我觉得就是版本的问题，你别用这个模型，去github上下载他最新的那个模型，2018的那个，就不出错了，我用这个运行之后就输出准确率什么的了。虽然还有点别的小错误，但大体已经可以了。我刚跑出来，你可以试试。

谢谢 我用了2018的模型也跑通了！！！

**Comment by taojin1992** [comment]
I got the same error when I used the pretrained mobileFaceNet and SqueezeNet models. I tried using the pretrained model 0f 20180402 and it went through. I can use the pretrained mobileFaceNet and SqueezeNet models in compare.py successfully but cannot use on validate_on_lfw.py. Is there any suggestion?

**Comment by HX1079299660** [comment]
I also have same problem，but I don't known what  to do .

`ValueError: Attempted to map inputs that were not found in graph_def: [label_batch:0, image_batch:0, phase_train:0]
`
