### ISSUE TITLE
This error, how to dealwith and my tensorflow version is tf1.12 "The name 'decode_image/cond_jpeg/is_png' refers to an Operation not in the graph." 

### ISSUE THREAD

**Issue by BennyYuan** [davidsandberg/facenet#955]
2019-01-20 13:50:41.258006: W tensorflow/core/graph/graph_constructor.cc:1265] Importing a graph with a lower producer version 24 into an existing graph with producer version 27. Shape inference will have run different parts of the graph with different producer versions.
Traceback (most recent call last):
  File "src/validate_on_lfw.py", line 164, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "src/validate_on_lfw.py", line 73, in main
    facenet.load_model(args.model, input_map=input_map)
  File "/sdaf/work/ymw/facenet/src/facenet.py", line 381, in load_model
    saver = tf.train.import_meta_graph(os.path.join(model_exp, meta_file), input_map=input_map)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1674, in import_meta_graph
    meta_graph_or_file, clear_devices, import_scope, **kwargs)[0]
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1696, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/meta_graph.py", line 841, in import_scoped_meta_graph_with_return_elements
    proto, import_scope=scope_to_prepend_to_names))
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1791, in from_proto
    import_scope=import_scope)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1699, in __init__
    self._init_from_proto(context_def, import_scope=import_scope)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1731, in _init_from_proto
    import_scope=import_scope)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1504, in __init__
    self._init_values_from_proto(values_def, import_scope=import_scope)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 1536, in _init_values_from_proto
    g.as_graph_element(op)._set_control_flow_context(self)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/yun/soft/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3550, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'decode_image/cond_jpeg/is_png' refers to an Operation not in the graph."

**Comment by manhngodh** [comment]
Duplicate of #852

**Comment by ZhuLY123** [comment]
so did you solve it ?

**Comment by kit57** [comment]
Try to install tensorflow1.7. It should do it
